spring:
  profiles:
    active: default
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/workbench
    username: root
    password: sampleDBPass9097!
  jpa:
    open-in-view: false
    properties:
      org:
        hibernate:
          envers:
            "[audit_table_suffix]": _history
            "[revision_field_name]": audit_id
            "[revision_type_field_name]": audit_type
            "[store_data_at_delete]": true

logging:
  level:
    web: ERROR
    org:
      hibernate:
        SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

server:
  servlet:
    context-path: /demo
    session:
      timeout: 30m
  error:
    path: /error