spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workbench
    username: root
    password: root
  jpa:
    open-in-view: false
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            revision_field_name: audit_id
            revision_type_field_name: audit_type
            store_data_at_delete: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

server:
  servlet:
    context-path: /demo
    session:
      timeout: 2000
