spring:
  profiles:
    active: default
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_8c62eb6cb171949
    username: bf307a52ec7f48
    password: fed99610
  jpa:
    open-in-view: false
    properties:
      org:
        hibernate:
          envers:
            "[audit_table_suffix]": _history
            "[revision_field_name]": audit_id
            "[revision_type_field_name]": audit_type
            "[store_data_at_delete]": true

logging:
  level:
    web: ERROR
    org:
      hibernate:
        SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

server:
  servlet:
    context-path: /demo
    session:
      timeout: 30m
  error:
    path: /error